language: r
r:
  - oldrel
  - release
  - devel
sudo: required
dist: trusty
before_install:
  - sudo apt-get update

after_success:
  - Rscript -e 'covr::codecov()'


addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
